pull_request_rules:
  - name: Automatic merge
    description: automerge to main with label automerge and branch protection passing
    conditions:
      - '#approved-reviews-by>1'
      - base=main
      - label=A:automerge
    actions:
      queue:
        name: default
